server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://mysql:3306/UserDatabase
    username: root
    password: "123456"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

jwt:
  signerKey: "iibCe8bCDuK8ziYesVMoeyJcZ6Lmp9jwwOGTMc7KzMYVi3wU18uypgq0Mh6YHNQN"