server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://mysql:3306/ProductDatabase
    username: root
    password: "123456"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

  mvc:
    problemdetails:
      enabled: true